### ISSUE TITLE
建议: 以全屏的方式增加贪吃蛇等程序

### ISSUE THREAD

**Issue by JackZhangCHN** [404name/winter#1]
建议：由于笔记本的倾斜角度需要考虑到梯形斜变的影响，建议可以通过全屏控制。同时在全屏下取消键盘，直接映射键盘。

**Comment by 404name** [comment]
晓得了（邮箱回复可还行）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JackZhangCHN"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 下午2:02
收件人:&nbsp;"404name/winter"<winter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[404name/winter] 建议: 以全屏的方式增加贪吃蛇等程序 (#1)




建议：由于笔记本的倾斜角度需要考虑到梯形斜变的影响，建议可以通过全屏控制。同时在全屏下取消键盘，直接映射键盘。

**Comment by JackZhangCHN** [comment]
> JackZhangCHN

高端！先close了

**Comment by 404name** [comment]
哈哈，之前第一次收到回复没搞清，原来是辅助邮箱提示，搞得我还以为是邮箱回复我的呢😂。我本来还想回复你：（不用那个界面就没有模拟笔记本的意义了），但那时候不熟悉github没找到地方回复😂。但后来我还是找到了解决方法，实现了能在梯形屏幕内玩的游戏了喔0.0，类似贪吃蛇，但相比于贪吃蛇我写的那个更复杂些。然后也谢谢你的建议0v0，我也后面才想去思考去折腾然后实现这个。
