### ISSUE TITLE
大佬可否放一下打印抛物线的测试代码？

### ISSUE THREAD

**Issue by JLHENRY-pixel** [404name/winter#5]

**Comment by 404name** [comment]
行，等我写完作业qwq就抛物线的demo代码加点注释上传再通知下你，大概下午4.。5点左右吧。（抛物线原理还是要去琢磨，我的算法也不是很精简，我等下在代码注释内尽量讲清楚些）

**Comment by JLHENRY-pixel** [comment]
> 行，等我写完作业qwq就抛物线的demo代码加点注释上传再通知下你，大概下午4.。5点左右吧。（抛物线原理还是要去琢磨，我的算法也不是很精简，我等下在代码注释内尽量讲清楚些）

太谢谢你了。
我的算法是Vx,Vy与0的关系分为4类，每一类逐一去写。你可以用二次方程的c/a判断正负然后得出t1,t2的正负，可以精简代码。

**Comment by 404name** [comment]
再等等哈，忘记下午有高数课了，下完课刚刚已经补充了很多说明，应该能看明白的，我吃完饭修改完就放上来😊

**Comment by JLHENRY-pixel** [comment]
> 再等等哈，忘记下午有高数课了，下完课刚刚已经补充了很多说明，应该能看明白的，我吃完饭修改完就放上来😊

多谢，麻烦你了

**Comment by 404name** [comment]
已放，在打砖块子目录下😊
