### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by korman** [404name/winter#6]
# 几点建议

* 不要使用压缩包格式，如果因为是exe的原因，可以把执行文件与txt放到压缩包里，然后打tag发release。
* 源码使用UTF-8，这几乎是统一的文件格式，通同性更强一些，除了早期的Visual Studio，没有哪个编辑器打不开的，而现在这个gbk的源码格式，vim等编辑器打开会乱码。
* 如果真喜欢纯C，还是多向linux&unix这个系统靠拢，至少要会写Makefile或者cmake等，一行#include <windows.h>就挡住很多人兴趣了……否则你的星会更多。
* 优化动画文件，如果喜欢字符动画，可以做个转换程序，把.txt转成二进制文件，0100完全可以替代"空格#空格空格"，提升加载速度，减少体积。做个宏判断，调试就txt。发布就直接读进二进制文件，if (1==chr) c = '#' else c = ' ';这样就好了

**Comment by 404name** [comment]
> # 几点建议
> * 不要使用压缩包格式，如果因为是exe的原因，可以把执行文件与txt放到压缩包里，然后打tag发release。
> * 源码使用UTF-8，这几乎是统一的文件格式，通同性更强一些，除了早期的Visual Studio，没有哪个编辑器打不开的，而现在这个gbk的源码格式，vim等编辑器打开会乱码。
> * 如果真喜欢纯C，还是多向linux&unix这个系统靠拢，至少要会写Makefile或者cmake等，一行#include <windows.h>就挡住很多人兴趣了……否则你的星会更多。
> * 优化动画文件，如果喜欢字符动画，可以做个转换程序，把.txt转成二进制文件，0100完全可以替代"空格#空格空格"，提升加载速度，减少体积。做个宏判断，调试就txt。发布就直接读进二进制文件，if (1==chr) c = '#' else c = ' ';这样就好了

感谢建议~，，之前大一还不大熟悉github用法，release，action，pages很多东西都是后面才摸索到的，然后之前代码都不规范标准😂，这个方面的话后面仓库继续更新下去会注意哒~。
