### ISSUE TITLE
符号怎么生成

### ISSUE THREAD

**Issue by XianMengxi** [404name/winter#7]
我想问一下up主这些符号是怎么生成的呀

**Comment by 404name** [comment]
特殊符号需要复制下来存好，下次用就方便了，用就直接粘贴打印就行，有很多字符是不支持很多平台的，最保守的就是全部用键盘上的字符，我后面的很多游戏都很少用特殊字符~

**Comment by XianMengxi** [comment]
不，我的意思是怎么把一个视频的特征变成符号，总不可能是自己“画“出来的吧？

**Comment by 404name** [comment]
b站搜  视频 字符画，就知道了(忘记回复了)
- 先视频把每帧导出来，就变成图片转字符画问题了
- 利用工具/python脚本，把图片解析成字符画
- 把每帧字符画放映就是了，肯定不自己画
