### ISSUE TITLE
关于您“模拟笔记本电脑”程序的问题

### ISSUE THREAD

**Issue by GustaveLi** [404name/winter#9]
您好，
我在完成计算机的大作业，希望用您的程序做一个参考。看了您“模拟笔记本电脑”程序后（版本已经附在下面），有如下不清楚的地方， 希望您能进一步解释：
1. 对代码第797行 ch == -32 不是很懂它的意思
2. 对于1378行的put_letter_to_computer函数和1401行的put_function_to_computer函数不明白它实现的原理和两个函数的关系，希望您加以解释并最好能对这两个函数写一点详细的注释
谢谢！
[大作业.txt](https://github.com/404name/winter/files/6463614/default.txt)

**Comment by 404name** [comment]
> 您好，
> 我在完成计算机的大作业，希望用您的程序做一个参考。看了您“模拟笔记本电脑”程序后（版本已经附在下面），有如下不清楚的地方， 希望您能进一步解释：
> 
> 1. 对代码第797行 ch == -32 不是很懂它的意思
> 2. 对于1378行的put_letter_to_computer函数和1401行的put_function_to_computer函数不明白它实现的原理和两个函数的关系，希望您加以解释并最好能对这两个函数写一点详细的注释
>    谢谢！
>    [大作业.txt](https://github.com/404name/winter/files/6463614/default.txt)

1.  -32是因为数字键盘左边的上下左右键位每个是由两个字符组成的，并且第一个字符转型值都是-32，你可以通过判断第一次拿去判断是否是上下左右，进而通过那边模拟wasd效果。
2. emm函数那个一个是将文字输入到屏幕对应的地方，一个是执行相应的方法。
tip：我最近都在忙我java大课设，可能没时间增加注释，这个代码是我一年前写的，我看着也头疼qaq。如果你是在做课设，我推荐哔哩哔哩搜视频跟着做。我的这些估计要我面对面讲才能懂，我有想过录制视频，但没太多时间。加油啦
